### ISSUE TITLE
Missing ffi in the dependencies

### ISSUE THREAD

**Issue by mensfeld** [takkii/himekuri_rust#1]
Hey.

When I install and require this gem, I see following error:

```
 cannot load such file -- ffi
```

this indicates that https://rubygems.org/gems/ffi is not in the gemspec and indeed it's not: https://my.diffend.io/gems/himekuri_rs/1.0.0#d2h-219235

it is in the gemfile but gemfile is not used when resolving gems in bundler.

**Comment by takkii** [comment]
Hello, Thank you for issues

```markdown
gem install ffi
```

try it

**Comment by mensfeld** [comment]
My point was, that you could add it to the gemspec dependencies and then it would be autoinstalled: https://guides.rubygems.org/specification-reference/#add_runtime_dependency

Do you want me to PR this?

**Comment by takkii** [comment]
日本語ですいません。このissuesは削除します。

必要ではありません、拒否します。
